//! UI chrome translation (English/Japanese). Scoped to labels, buttons,
//! and headers this crate owns — `HarmonizationResult::why`/`why_not`'s
//! own generated text (from mokuren itself) stays English; translating
//! rule/reason prose is a separate, much larger effort this demo isn't
//! attempting.

use leptos::prelude::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Lang {
    En,
    Ja,
}

impl Lang {
    pub fn label(self) -> &'static str {
        match self {
            Lang::En => "EN",
            Lang::Ja => "JA",
        }
    }

    pub fn from_label(label: &str) -> Lang {
        match label {
            "JA" => Lang::Ja,
            _ => Lang::En,
        }
    }
}

pub fn provide_lang() -> RwSignal<Lang> {
    let lang = RwSignal::new(Lang::En);
    provide_context(lang);
    lang
}

pub fn use_lang() -> RwSignal<Lang> {
    use_context::<RwSignal<Lang>>().expect("provide_lang must run before use_lang")
}

macro_rules! translations {
    ($($name:ident => ($en:expr, $ja:expr $(,)?),)*) => {
        $(
            pub fn $name(lang: Lang) -> &'static str {
                match lang {
                    Lang::En => $en,
                    Lang::Ja => $ja,
                }
            }
        )*
    };
}

translations! {
    tagline => ("Explainable Harmony", "説明可能な和声付け"),
    melody_label => ("Melody", "旋律"),
    key_label => ("Key", "調"),
    mode_major => ("major", "長調"),
    mode_minor => ("minor", "短調"),
    beam_width_label => ("Beam width", "ビーム幅"),
    harmonize_button => ("Harmonize", "和声付け"),
    harmonization_header => ("Harmonization", "和声進行"),
    alternatives_header => ("Alternatives", "候補"),
    position_label => ("Position", "位置"),
    generated_label => ("generated", "生成"),
    retained_label => ("retained", "採用"),
    rejected_label => ("rejected", "却下"),
    status_selected => ("SELECTED", "選択"),
    status_valid => ("valid", "有効"),
    status_rejected => ("rejected", "却下"),
    error_prefix => ("Error: ", "エラー: "),
    why_note => (
        "(reasoning below is generated by mokuren itself, in English)",
        "(以下の説明はmokuren自身が生成したもので、英語のままです)",
    ),

    melody_tip => (
        "Space-separated pitch+octave, e.g. C4 D4 E4 — the fixed soprano line mokuren harmonizes. Every note is a quarter note.",
        "空白区切りの「音名+オクターブ」、例: C4 D4 E4 — mokurenが和声付けする固定のソプラノ声部です。すべて四分音符として扱われます。",
    ),
    key_tip => (
        "Tonic pitch class, e.g. C, F#, Bb.",
        "主音の音名。例: C、F#、Bb。",
    ),
    mode_tip => (
        "Major or (natural + harmonic) minor — changes which chord qualities are diatonic and unlocks the raised-leading-tone V/V7/vii° in minor.",
        "長調か(自然的+和声的)短調か。調によりダイアトニックコードの種類が変わり、短調では導音を上げたV/V7/vii°が使えるようになります。",
    ),
    beam_width_tip => (
        "How many partial harmonizations the search keeps at each step. Wider = more thorough but slower; too narrow can miss the best (or any) path.",
        "各ステップで探索が保持する部分和声の候補数。広いほど網羅的だが遅くなり、狭すぎると最良の(あるいはどの)経路も見つからないことがあります。",
    ),
    diagnostics_tip => (
        "How many voicings the search generated in total, how many passed every hard rule (retained), and how many were rejected.",
        "探索全体で生成された声部配置の総数、すべての必須ルールを通過した数(採用)、および却下された数。",
    ),
    progression_tip => (
        "Click a chord to see why it was chosen and what else was considered at that position.",
        "コードをクリックすると、その位置で選ばれた理由と他に検討された候補を確認できます。",
    ),
    alternative_tip => (
        "Click to see why this alternative was (or wasn't) chosen over the selected chord.",
        "クリックすると、この候補が選ばれたコードに対してなぜ採用/不採用だったかを確認できます。",
    ),

    beam_race_header => ("Beam Search Race", "ビームサーチ・レース"),
    beam_race_tip => (
        "Re-harmonizes the current melody at several beam widths, so you can see exactly how wide a beam this melody actually needs.",
        "現在の旋律を複数のビーム幅で再和声付けし、この旋律に実際どれだけの幅が必要かを確認できます。",
    ),
    beam_race_button => ("Run beam search race", "ビームサーチ・レースを実行"),
    beam_race_width_col => ("Width", "幅"),
    beam_race_result_col => ("Result", "結果"),
    beam_race_candidates_col => ("Candidates evaluated", "評価した候補数"),
    beam_race_runtime_col => ("Runtime (ms)", "実行時間 (ms)"),
    beam_race_success => ("SUCCESS", "成功"),
    beam_race_fail => ("FAIL", "失敗"),

    explain_tab_label => ("About", "使い方"),
    explain_intro => (
        "mokuren harmonizes a melody into four voices (SATB) and can explain every decision it makes. This demo has two parts:",
        "mokurenは旋律を4声体(SATB)に和声付けし、すべての判断を説明できます。このデモには2つの機能があります。",
    ),
    explain_compose_body => (
        "Enter a melody, key, and mode, then Harmonize. Click any chord in the result to see why() it was chosen, and click an alternative to see why_not() it wasn't.",
        "旋律・調・長短を入力してHarmonizeを押します。結果のコードをクリックするとなぜそのコードが選ばれたか(why())、候補をクリックするとなぜ選ばれなかったか(why_not())を確認できます。",
    ),
    explain_search_body_1 => (
        "mokuren builds a harmonization one chord at a time. At each step there are many possible voicings; trying every combination for every chord would be too slow, so mokuren only keeps a limited number of the best partial harmonizations and discards the rest — that limit is the beam width.",
        "mokurenは和音を1つずつ順番に決めていきます。各ステップには多数の配置(voicing)候補があり、すべての組み合わせを試すと遅すぎるため、mokurenは各ステップで上位いくつかの部分的な和声進行だけを残し、残りは切り捨てます。この「残す数」がビーム幅です。",
    ),
    explain_search_body_2 => (
        "A narrow beam is fast but can lose the eventual best (or only) path early; a wide beam explores more but costs more candidates and runtime. This race re-harmonizes the same melody at several widths so you can see exactly how wide a beam it actually needs.",
        "幅が狭いと速いですが、本当に良い(あるいは唯一の)経路を早い段階で捨ててしまうことがあります。幅が広いとより多くの経路を探索できますが、候補数と実行時間が増えます。このレースは同じ旋律を複数の幅で再和声付けし、この旋律に実際どれだけの幅が必要かを確認できるようにしたものです。",
    ),
    explain_width => (
        "How many partial harmonizations mokuren kept alive at each step during this run.",
        "この実行で、各ステップにおいてmokurenが保持した部分的な和声進行の数。",
    ),
    explain_candidates => (
        "The total number of chord voicings mokuren generated and scored across the whole search at this width.",
        "この幅での探索全体で、mokurenが生成・採点した和音配置の総数。",
    ),
    explain_runtime => (
        "Wall-clock time for the search at this width, measured in this browser.",
        "この幅での探索にかかった実時間(このブラウザでの計測値)。",
    ),
}
